name: Linters

on:
  pull_request: { }

jobs:

  linters:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install and Run Pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Download Semgrep rules
        run: git clone --depth 1 https://github.com/frappe/semgrep-rules.git frappe-semgrep-rules

      - uses: returntocorp/semgrep-action@v1
        env:
            SEMGREP_TIMEOUT: 120
        with:
            config: >-
              r/python.lang.correctness
              ./frappe-semgrep-rules/rules